name: dp_gbdt_evaluation
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cython=0.29.*
  - hyperopt=0.2.*
  - numpy=1.21.*
  - pandas=1.4.*
  - ray-tune=1.6.*
  - scikit-learn=1.1.*
#  - scipy=1.7.*
  - spdlog=1.10.*
  - tune-sklearn=0.4.*